stages:
  data_ingestion:
    cmd: python src/medical_nlp/pipeline/stage_01_data_ingestion.py
    deps:
      - src/medical_nlp/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/ca-independent-medical-review

  prepare_base_model:
    cmd: python src/medical_nlp/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/medical_nlp/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - CLASSES

    outs:
     - artifacts/prepare_base_model

  model_training:
    # code to run the specific pipeline
    cmd: python src/medical_nlp/pipeline/stage_03_model_training.py
    # dependencies
    deps:
      - src/medical_nlp/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/ca-independent-medical-review
      - artifacts/prepare_base_model
    # parameter dependencies
    params:
     - BATCH_SIZE
     - EPOCHS
     - LEARNING_RATE
     - MODEL_NAME
    # outputs
    outs:
     - artifacts/training/