# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nlpmedicalapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://saeidaiclone.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4bc942ad7e2844c88c230d667123664b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4a8c4e511e1e4952b6f2846c13507070 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: saeidaiclone.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4bc942ad7e2844c88c230d667123664b }}/medical:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nlpmedicalapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a33ad631670e4513a3d4b8e08660b9eb }}
        images: 'saeidaiclone.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4bc942ad7e2844c88c230d667123664b }}/medical:${{ github.sha }}'